title: 'Terminal Blog'
description: "Meu blog pessoal com tema inspirado em terminais linux."
baseurl: "/terminal"
url: "https://othiagob.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: light 

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

# GitHub Pages / Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Sass
sass:
  style: compressed

# kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
